[env]
TERM = "xterm-256color"

[font]
size = 12
[font.normal]
family = "JetBrains Mono Nerd Font"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
regex = "(https:|http:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
[hints.enabled.mouse]
enabled = true
mods = "Control"

[selection]
save_to_clipboard = true

[window]
opacity = 0.9
dynamic_padding = false
padding = { x=10, y=10 }

[general]
import = ["~/.config/alacritty/themes/gruvbox_material_hard_dark.toml"]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"
